### ISSUE TITLE
MLM doesn't work when Safari's cross-site tracking protection is enabled.

### ISSUE THREAD

**Issue by pappasilenus** [acbeers/mastodonlm#22]
First off, thank you for a very useful app!  

Safari Version 16.2 (18614.3.7.1.5) on macOS Ventura 13.1 (22C65)

The site only works when the "prevent cross-site tracking" selection is disabled, as shown below.  The error in the JS console is pasted below that.  

Not sure if this is fixable, or you want to call it out on the front page.

<img width="768" alt="Screenshot 2022-12-31 at 10 49 31" src="https://user-images.githubusercontent.com/36678903/210153161-c6fa8369-b081-4d3b-9bbe-be6d9a6610d9.png">

[Debug] topee.hello(tabId: 11689417243958828, referrer: "https://acbeers.github.io/mastodonlm/callback?domain=mastodon.social&code=Or9LqnZp0cCtWYoqy5hNYTtUu7GOlNUk6yNgNErRaxk&state=None", historyLength: 4) @ https://acbeers.github.io/mastodonlm/?/callback&domain=mastodon.social~and~code=Or9LqnZp0cCtWYoqy5hNYTtUu7GOlNUk6yNgNErRaxk~and~state=None -> 11689417243958828
[Error] Failed to load resource: the server responded with a status of 500 () (callback, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (meta, line 0)
[Error] Failed to load resource: the server responded with a status of 401 () (auth, line 0)
[Log] {status: "bad_host"} (main.e70a5a07.js, line 2)

**Comment by pappasilenus** [comment]
Update: The protection only needs to be disabled on first authentication and login.  Once that's done, the app appears to work. The fix might be as simple as adding a CNAME for some authentication resource used by the app?  Not sure.

**Comment by acbeers** [comment]
Thanks for the report!  However, I run the app successfully with "prevent cross site tracking" enabled in Safari 16.1 and macOS 13, but let me try Safari 16.2 / macOS 13.1

**Comment by acbeers** [comment]
MLM works for me on Safari 16.2, macOS 13.1 with "prevent cross site tracking" enabled.

**Comment by acbeers** [comment]
As above, this doesn't appear to be an issue.
