### ISSUE TITLE
Create/Delete a list

### ISSUE THREAD

**Issue by kvithayathil** [acbeers/mastodonlm#50]
Would it be possible to have the ability to create (or even delete) a list on the fly? Sometimes I discover a follow that doesn't quite fit the current set of lists I have and would like to put them in a newly created one

**Comment by acbeers** [comment]
Already there!  Click the hamburger menu at the upper left and create away!  To delete, click the trash can when you hover over a list name!

**Comment by acbeers** [comment]
As above, already implemented.
