### ISSUE TITLE
Not recognizing "pettingzoo.co" as valid host

### ISSUE THREAD

**Issue by DirtyPeanut** [acbeers/mastodonlm#60]
Summary:
Web page does not recognize "pettingzoo.co" as valid host name

Repro:
1. Enter "pettingzoo.co" as host name
2. Click "Go"

Observed: Error returned "Please enter a hostname of a Mastodon server (e.g. mastodon.social)"

Expected: Hostname recognized and continues to next step.

**Comment by acbeers** [comment]
pettingzoo.co is returning an empty response and a 420 status on its app creation endpoint /api/v1/apps, which ends up throwing a "network error" in the mastodon library I'm using which I signal as "bad host" as I'm not getting a valid response to the API call.  pettingzoo is running Mastodon 4.1.0, and so is mastodon.social, which is working.

**Comment by acbeers** [comment]
This behavior can be seen via the following command line:

curl -X POST \
        -F 'client_name=Test Application' \
        -F 'redirect_uris=urn:ietf:wg:oauth:2.0:oob' \
        -F 'scopes=read write push' \
        -F 'website=https://myapp.example' \
        https://pettingzoo.co/api/v1/apps

This returns nothing.  When I run this for mastodon.social, I get back a JSON response.

**Comment by acbeers** [comment]
Thanks to the site admin, I found that this incantation works:

curl -X POST \
        -F 'client_name=Test Application' \
        -F 'redirect_uris=urn:ietf:wg:oauth:2.0:oob' \
        -F 'scopes=read write push' \
        -F 'website=https://myapp.example' -A mastodonlm \
        https://pettingzoo.co/api/v1/apps

Setting a user-agent on the create_app call, which works differently than on authenticated methods, should fix this.

**Comment by acbeers** [comment]
Many calls in the Mastodon library I'm using let me set a user-agent.  The create_app call does not, but does let me pass a session object pre-configured with headers that I want.
