### ISSUE TITLE
mastodon.social is not supportet even though suggested.

### ISSUE THREAD

**Issue by mogoh** [acbeers/mastodonlm#67]
If I enter `mastodon.social` as domain I get “_Looks like your domain is not currently supported!_” even if it is a suggested domain.

![image](https://github.com/acbeers/mastodonlm/assets/580975/f5a23cbb-af73-49d4-8788-9ed1cee86524)

**Comment by acbeers** [comment]
There was a blocklist issue.  I've fixed the data problem, will update the management code next.

**Comment by mogoh** [comment]
Thank you!
